In [1]:
import pandas as pd

In [2]:
DB_PATH = "runs_index.csv"

DB = pd.read_csv(DB_PATH, index_col=0)
DB.head()

,E_VF_species_test,E_VF_species_train,E_VF_test,E_VF_train,E_spec_species_test,E_spec_species_train,E_spec_test,E_spec_train,E_trajectory_species_test,E_trajectory_species_train,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_03lcWbxB,"[427836782.28273803, 1.212274891427212e+18, 17...","[15.727485446392942, 3.9426324331804126, 311.9...",4.040916e+17,110.536864,"[0.9997990781388215, 217398.78219042526, 1.845...","[0.9985434811346798, 8.018886362415799, 2.2884...",6.151205e+28,7.628302e+28,"[6354.550388504019, 564861.0709334062, 6.05354...","[5.460099103729034, 287.9805002845772, 30.4849...",...,2,10000,12,150,False,NaN,NaN,NaN,NaN,NaN
run_06NO44XO,"[449841090.39906424, 8.214972332475935e+18, 69...","[224.6813811009467, 121.35761189647442, 399.32...",2.738324e+18,248.453052,"[0.9997731664799244, 2943178.807948509, 4.2304...","[0.9993745167477197, 0.38157941713444804, 1.32...",1.410165e+30,4.410471e+26,"[3.79454615161105e+23, 2.5501928049415273e+25,...","[2936.575547258823, 449433.57037484297, 26000....",...,2,10000,12,150,False,NaN,NaN,NaN,NaN,NaN
run_08Q75yMZ,"[10446623.782296566, 1194.5543581813756]","[10.715507911567633, 1.5986795653726147]",5.223909e+06,6.157094,"[0.5359738312047515, 19239.064993098116]","[0.6441668171710596, 3.827308649691848]",9.619800e+03,2.235738e+00,"[0.9999085679779263, 1.2339071350922954]","[0.9141669227994335, 1.0000010983614722]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_09nnvX1K,"[1.2659853792184483, 0.27912456983322287, 1768...","[9.478247367860889e-08, 9.053455205637821e-08,...",1.054764e+29,0.691589,"[0.9999999999833352, 0.9999996564257434, 0.997...","[0.9999999993400052, 0.9999993127647504, 0.993...",2.368737e+304,inf,"[6657491.871020809, 1914071.3614436523, 9.6802...","[687993.1519896915, 15090.967524426405, 8.8297...",...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_0A7kQGIb,"[414666.1270138581, 327076.4755736458, 50546.1...","[0.38842384968594873, 0.46997580389881305, 0.5...",1.090156e+05,0.415268,"[0.6113673157429158, 0.5238520345689427, 0.742...","[0.9711755340534483, 0.572885004256412, 0.8860...",2.734886e+23,2.830212e+14,"[195565883779.50558, 259408582138.439, 4644798...","[136.9040783305313, 2062.6217919904807, 420916...",...,2,10000,16,150,False,qr,NaN,NaN,NaN,NaN

In [5]:
DB.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1400 entries, run_03lcWbxB to run_zyVsxSy6
Data columns (total 46 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   E_VF_species_test           822 non-null    object
 1   E_VF_species_train          822 non-null    object
 2   E_VF_test                   779 non-null    float64
 3   E_VF_train                  818 non-null    float64
 4   E_spec_species_test         822 non-null    object
 5   E_spec_species_train        822 non-null    object
 6   E_spec_test                 779 non-null    float64
 7   E_spec_train                818 non-null    float64
 8   E_trajectory_species_test   822 non-null    object
 9   E_trajectory_species_train  822 non-null    object
 10  E_trajectory_test           779 non-null    float64
 11  E_trajectory_train          818 non-null    float64
 12  collocation_time            1400 non-null   float64
 13  computer                    1397 non-null   object
 14  derivmatch_time             1400 non-null   float64
 15  err-file                    1397 non-null   object
 16  init                        1398 non-null   object
 17  model                       1398 non-null   object
 18  model_width                 402 non-null    float64
 19  n_params                    1400 non-null   int64
 20  ncol                        1398 non-null   float64
 21  out-file                    1397 non-null   object
 22  param                       1400 non-null   object
 23  pretraining                 1397 non-null   object
 24  problem                     1400 non-null   object
 25  profile                     1400 non-null   object
 26  seed                        1400 non-null   int64
 27  shap-hessian                906 non-null    object
 28  shapovalova_time            1398 non-null   float64
 29  shoot-iters                 1398 non-null   float64
 30  shooting_time               1398 non-null   float64
 31  sigma                       1398 non-null   float64
 32  timestamp                   1398 non-null   object
 33  training                    1397 non-null   object
 34  training_time               1400 non-null   float64
 35  cfg.amr_rounds              1400 non-null   int64
 36  cfg.depth                   1400 non-null   int64
 37  cfg.dm_iters                1400 non-null   int64
 38  cfg.hidden                  1400 non-null   int64
 39  cfg.lm_iters                1400 non-null   int64
 40  cfg.signed_loss             1400 non-null   bool
 41  cfg.linsolve                254 non-null    object
 42  use_collocation             3 non-null      object
 43  use_derivmatch              3 non-null      object
 44  shapovalova                 1 non-null      object
 45  shooting                    1 non-null      object
dtypes: bool(1), float64(15), int64(7), object(23)
memory usage: 504.5+ KB

In [6]:
print(DB["model"].unique())
print(DB["problem"].unique())
print(DB["pretraining"].unique())
print(DB["training"].unique())

['mlp' 'stiff' 'GELU-scaled' nan]
['rober' 'vanderpol' 'pollu' 'hires' 'orego' 'davis-skodje']
['derivmatch' 'none' nan]
['shooting' 'collocation' 'none' 'shapovalova' nan]

In [7]:
DB[["model", "training", "pretraining"]].drop_duplicates()

                    model     training pretraining
run_dir
run_03lcWbxB          mlp     shooting  derivmatch
run_08Q75yMZ        stiff     shooting        none
run_09nnvX1K          mlp  collocation        none
run_0A7kQGIb          mlp  collocation  derivmatch
run_0BLmyHm6          mlp         none  derivmatch
run_0BrnUKSf        stiff         none  derivmatch
run_0CWrKVsW  GELU-scaled         none  derivmatch
run_0Gfl62cO  GELU-scaled  collocation        none
run_0H5EbMNc        stiff  collocation  derivmatch
run_0HTw2xgv        stiff  collocation        none
run_0Lq1bPrm          mlp  shapovalova  derivmatch
run_0SBGYTBw  GELU-scaled     shooting        none
run_0ilswGVa  GELU-scaled  shapovalova        none
run_0oHxpKt3          mlp  shapovalova        none
run_0pAVzUCM        stiff  shapovalova  derivmatch
run_0pSCJcJK          mlp     shooting        none
run_18leAdxZ  GELU-scaled  collocation  derivmatch
run_2cXb4Ci9  GELU-scaled     shooting  derivmatch
run_2tL35rX6  GELU-scaled  shapovalova  derivmatch
run_3Pph53ey        stiff     shooting  derivmatch
run_9ZBK1iOn        stiff  shapovalova        none
run_9zWKNJ3v          NaN          NaN         NaN
run_Uve46cZI        stiff          NaN         NaN

In [10]:
# DB = DB[DB["E_vf_species_train"] != "NaN"]
nn = DB[(DB["problem"] == "vanderpol") & (DB["model"] == "stiff") & (DB["pretraining"] == "derivmatch") & (DB["training"] == "collocation")]
# nn = DB[(DB["problem"] == "pollu") & (DB["model"] == "stiff") & (DB["pretraining"] == "derivmatch") & (DB["training"] == "collocation")]
nn

,E_VF_species_test,E_VF_species_train,E_VF_test,E_VF_train,E_spec_species_test,E_spec_species_train,E_spec_test,E_spec_train,E_trajectory_species_test,E_trajectory_species_train,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_5wDGqVf4,"[0.002168162924740981, 7.836730598693145]","[0.00019857656091700079, 0.0010671054879047277]",3.919449,0.000633,"[0.02220428950497137, 0.21132279086323014]","[0.01844380935074132, 0.07788626866569713]",0.116764,0.048165,"[0.04518048980130794, 0.9652136957763755]","[0.24451821149562464, 0.5512786032442389]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_AdvfCqR0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_E9ArQetU,"[0.010019643667308035, 6.831571703173638]","[7.299596789547037e-05, 0.0022769723690544007]",3.420796,0.001175,"[0.03089288937164262, 0.021294555191646018]","[0.04769927693069452, 0.29841395979420204]",0.026094,0.173057,"[1.1337242617658724e-05, 0.22686769053944952]","[0.007614348737800922, 0.2308587951384612]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_EFWPTR8T,"[0.010019643667308035, 6.831571703173638]","[7.299596789547037e-05, 0.0022769723690544007]",3.420796,0.001175,"[0.03089288937164262, 0.021294555191646018]","[0.04769927693069452, 0.29841395979420204]",0.026094,0.173057,"[1.1337242617658724e-05, 0.22686769053944952]","[0.007614348737800922, 0.2308587951384612]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_Ez3T7npt,"[0.0025658761273894045, 7.851168470428202]","[0.00024233537898191493, 0.0032099468712698375]",3.926867,0.001726,"[0.048033674927017204, 0.03158068792901949]","[0.024475651553433356, 0.1440329762444342]",0.039807,0.084254,"[0.04968781619953609, 55779.52593749643]","[0.01630848152930572, 0.46239267905412423]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_JRn6dPBo,"[0.00015863580124642992, 0.1254211474101895]","[8.168891875850636e-05, 0.004090450378977941]",0.062790,0.002086,"[0.02195888569441102, 0.13524999112793384]","[0.013360632984547847, 0.12182617178878585]",0.078604,0.067593,"[0.022805636215005656, 0.5779620875701643]","[0.17631874706895295, 0.5288870960052345]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_KkOP3PEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_QryaK41J,"[0.002168162924740981, 7.836730598693145]","[0.00019857656091700079, 0.0010671054879047277]",3.919449,0.000633,"[0.02220428950497137, 0.21132279086323014]","[0.01844380935074132, 0.07788626866569713]",0.116764,0.048165,"[0.04518048980130794, 0.9652136957763755]","[0.24451821149562464, 0.5512786032442389]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_UeuX69DL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_YH35fGpK,"[0.00015863580124642992, 0.1254211474101895]","[8.168891875850636e-05, 0.004090450378977941]",0.062790,0.002086,"[0.02195888569441102, 0.13524999112793384]","[0.013360632984547847, 0.12182617178878585]",0.078604,0.067593,"[0.022805636215005656, 0.5779620875701643]","[0.17631874706895295, 0.5288870960052345]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_a2uHaghT,"[0.0866918366220469, 10.838955889729625]","[0.0023528108563422964, 0.008692083781786911]",5.462824,0.005522,"[0.1073291227652575, 0.3729043328692463]","[0.13940995369149217, 0.12106403015773516]",0.240117,0.130237,"[2.747064315121089, 902.9736963318553]","[1.2251986558474215, 0.9996276616375744]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_d8GKdWVm,"[0.0004315252062342147, 0.37060261685302776]","[0.0004600493147760376, 0.016417882051249992]",0.185517,0.008439,"[0.007714815915231365, 0.06921888835114452]","[0.005577371453465734, 0.1830966957941655]",0.038467,0.094337,"[0.10518227167967087, 2.515934470871907]","[0.5679182770926233, 1.1018755393240711]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_oVLbHSe1,"[0.0866918366220469, 10.838955889729625]","[0.0023528108563422964, 0.008692083781786911]",5.462824,0.005522,"[0.1073291227652575, 0.3729043328692463]","[0.13940995369149217, 0.12106403015773516]",0.240117,0.130237,"[2.747064315121089, 902.9736963318553]","[1.2251986558474215, 0.9996276616375744]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_plAVbXsz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_rOYFdDnk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_sGqguKPi,"[0.0004315252062342147, 0.37060261685302776]","[0.0004600493147760376, 0.016417882051249992]",0.185517,0.008439,"[0.007714815915231365, 0.06921888835114452]","[0.005577371453465734, 0.1830966957941655]",0.038467,0.094337,"[0.10518227167967087, 2.515934470871907]","[0.5679182770926233, 1.1018755393240711]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN

In [16]:
DB.keys()

Index(['E_VF_species_test', 'E_VF_species_train', 'E_VF_test', 'E_VF_train',
       'E_spec_species_test', 'E_spec_species_train', 'E_spec_test',
       'E_spec_train', 'E_trajectory_species_test',
       'E_trajectory_species_train', 'E_trajectory_test', 'E_trajectory_train',
       'collocation_time', 'computer', 'derivmatch_time', 'err-file', 'init',
       'model', 'model_width', 'n_params', 'ncol', 'out-file', 'param',
       'pretraining', 'problem', 'profile', 'seed', 'shap-hessian',
       'shapovalova_time', 'shoot-iters', 'shooting_time', 'sigma',
       'timestamp', 'training', 'training_time', 'cfg.amr_rounds', 'cfg.depth',
       'cfg.dm_iters', 'cfg.hidden', 'cfg.lm_iters', 'cfg.signed_loss',
       'cfg.linsolve', 'use_collocation', 'use_derivmatch', 'shapovalova',
       'shooting'],
      dtype='object')

In [13]:
vdp1 = DB[(DB["problem"] == "vanderpol") & (DB["seed"] == 12)]
vdp1

,E_VF_species_test,E_VF_species_train,E_VF_test,E_VF_train,E_spec_species_test,E_spec_species_train,E_spec_test,E_spec_train,E_trajectory_species_test,E_trajectory_species_train,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_1MJPRoKf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_2Jf27enp,"[6543086.600966761, 6222.9899103936705]","[6.886890423473277, 4.020839124007737]",3.274655e+06,5.453865,"[0.3502426323064126, 3255.8750302070785]","[0.43845370819059254, 1.3835011952963172]",1628.112636,0.910977,"[1.0182168149553867, 7.322835800697152]","[0.9462718583915374, 1.0000109455039379]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_2KX3LvwX,"[0.04502975731259024, 20.528627574146945]","[0.009006070240685927, 0.023644664516909553]",1.028683e+01,0.016325,"[0.13095822034465762, 0.6485659477509659]","[0.15650771804507324, 0.3135228500739336]",0.389762,0.235015,"[2.5412108118329675, 1.1656023274365235]","[1.6382004242993573, 0.999462141910917]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_2cXb4Ci9,"[0.7111518033715687, 3925.024591778816]","[0.039400805284520724, 2.9243398022934226]",1.962868e+03,1.481870,"[1.4049379619536801, 0.8763452004129324]","[1.094795853471226, 0.5708125261672032]",1.140642,0.832804,"[0.9991492848055747, 1.1258651401825244]","[0.7200753882317986, 1.0000171585728859]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_4MRZ6jvw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_4Q869pti,"[0.7680620202390948, 1.0336972779025981]","[1.0000819127927314, 1.0000021118671656]",9.008796e-01,1.000042,"[0.9998469351519865, 0.9998128636159662]","[0.9998530996760038, 0.9999814081008509]",0.999830,0.999917,"[1.0783555149066084, 108673.54467194602]","[1.1707909018370444, 1.0008193116242978]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_4UfHofXn,"[3716.7601980312443, 10849.36031649421]","[0.05927316872302511, 0.07300434829136467]",7.283060e+03,0.066139,"[0.5366486757584011, 13.301173338612863]","[0.5344494667460944, 0.34054706465009704]",6.918911,0.437498,"[0.9987803088152293, 35.245321755733045]","[0.7725458399880384, 1.0000367749987504]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_59oWj9tF,"[5384710.844733585, 462.9525196877893]","[6.125303491431223, 4.47949616377159]",2.692587e+06,5.302400,"[0.3705906741774335, 3110.4579739085257]","[0.42704667156636517, 1.475958266658364]",1555.414282,0.951502,"[1.0001734297943128, 15.478402446273572]","[0.9098527524491985, 1.0000205370234845]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_6htkcYWO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_6kcc1goF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_9ZD8cDMb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_BdmsU23Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_ByrM0GZ8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_CCc8Tb1V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_CMR4BCYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_CUNu6zUG,"[3716.7601980312443, 10849.36031649421]","[0.05927316872302511, 0.07300434829136467]",7.283060e+03,0.066139,"[0.5366486757584011, 13.301173338612863]","[0.5344494667460944, 0.34054706465009704]",6.918911,0.437498,"[0.9987803088152293, 35.245321755733045]","[0.7725458399880384, 1.0000367749987504]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_FIICVUPQ,"[0.2140858998630332, 68.13705553232458]","[0.3652780558951259, 0.256222213059135]",3.417557e+01,0.310750,"[1.436163550968426, 0.8272709847289196]","[24.12056299736634, 0.699262862854182]",1.131717,12.409913,"[1.1145381883448073, 38.35509220644244]","[1.0427385887856073, 1.000017675027972]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_IJaad5HS,"[6543086.600966761, 6222.9899103936705]","[6.886890423473277, 4.020839124007737]",3.274655e+06,5.453865,"[0.3502426323064126, 3255.8750302070785]","[0.43845370819059254, 1.3835011952963172]",1628.112636,0.910977,"[1.0182168149553867, 7.322835800697152]","[0.9462718583915374, 1.0000109455039379]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_IzVyuqsi,"[0.8514574859061784, 4.715023435980673]","[1.0433541780517808, 0.9998144385006013]",2.783240e+00,1.021584,"[0.9995987450403291, 0.9985378070833432]","[0.9991233293608478, 0.9987865489274815]",0.999068,0.998955,"[1.4111665182858493, 289.63004355724723]","[0.7766466657311836, 0.9536687833164801]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_JgGyD6Qb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_N6ki4SLO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_NbHfewgV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_S3pDx8Dc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_V4foGNTC,"[616.7322057034007, 32332.30436570048]","[5.880567685035479, 24.22645858556966]",1.647452e+04,15.053513,"[5.8208060367707315, 1.7456959173614552]","[159.87029099692933, 0.970553634201887]",3.783251,80.420422,"[1.2174072561912916, 3.138585522504879]","[0.8288708661784351, 0.9988589596226078]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_V8vGwpsd,"[0.04502975731259024, 20.528627574146945]","[0.009006070240685927, 0.023644664516909553]",1.028683e+01,0.016325,"[0.13095822034465762, 0.6485659477509659]","[0.15650771804507324, 0.3135228500739336]",0.389762,0.235015,"[2.5412108118329675, 1.1656023274365235]","[1.6382004242993573, 0.999462141910917]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_X8H6w7Nv,"[0.005559503140102689, 10.630848932317774]","[0.6733204005580575, 0.9402321095180544]",5.318204e+00,0.806776,"[0.13160299555970648, 0.9389246496470462]","[0.3772803859482321, 0.9993979355571085]",0.535264,0.688339,"[1.603641298128818, 8818.1903718599]","[1.0578088692267382, 0.9998588795073206]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_YbW9DQXs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_Yk23lx21,"[29.89163908583933, 15.745255320956431]","[0.998224714262628, 0.9999859077674683]",2.281845e+01,0.999105,"[0.999032302437426, 0.9932825064300329]","[0.9995864486259397, 0.999929147263686]",0.996157,0.999758,"[2.355886824892657, 20833.79774498835]","[0.5531576730049363, 1.0333552186566515]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_a2uHaghT,"[0.0866918366220469, 10.838955889729625]","[0.0023528108563422964, 0.008692083781786911]",5.462824e+00,0.005522,"[0.1073291227652575, 0.3729043328692463]","[0.13940995369149217, 0.12106403015773516]",0.240117,0.130237,"[2.747064315121089, 902.9736963318553]","[1.2251986558474215, 0.9996276616375744]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_bm0tMVBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_dmG8mHuF,"[1.1009906197214596, 1.8457338235695746]","[0.5037150945330613, 1.004245424271172]",1.473362e+00,0.753980,"[0.9818780312706737, 0.9932065621084535]","[0.9837605468904762, 0.9999856916021699]",0.987542,0.991873,"[1.2049275318711625, 8.159172308428124]","[1.2808629746099855, 0.9987260535805292]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_f01RPzsB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_fYLeYU4y,"[5384710.844733585, 462.9525196877893]","[6.125303491431223, 4.47949616377159]",2.692587e+06,5.302400,"[0.3705906741774335, 3110.4579739085257]","[0.42704667156636517, 1.475958266658364]",1555.414282,0.951502,"[1.0001734297943128, 15.478402446273572]","[0.9098527524491985, 1.0000205370234845]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_gKwo4E3L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_hFI32hy7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_hP77gWym,"[0.015726159359047524, 57.183918848425435]","[0.001480285492817961, 0.04132704151788958]",2.859982e+01,0.021404,"[0.2818170659245788, 0.3699615911321166]","[0.3293540472331495, 0.15508432112863618]",0.325889,0.242219,"[1.0249019969853161, 4.64495574383555]","[1.060008496537618, 1.000319198677067]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_hqsYpKzi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_i86bSKOp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_kKtsBFQg,"[0.023877349504234927, 3.403558341152824]","[0.6363637703376884, 0.9436439907424117]",1.713718e+00,0.790004,"[0.13087569054812254, 0.07441417737585886]","[0.287384499866498, 0.9944856079070108]",0.102645,0.640935,"[1.5754064557390624, 3874.616329874312]","[0.9745373225245386, 0.9994055822825074]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_kpAH7mr1,"[53.99544799365822, 5.763583098457788]","[0.9832047746917284, 0.9999904203744207]",2.987952e+01,0.991598,"[0.9974982690846428, 1.1090597532403121]","[0.9982658857654343, 0.9998711266327375]",1.053279,0.999069,"[0.9734261072897467, 1.449713300775515]","[0.8037917423721205, 1.0002178935981694]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_l9XKFt0b,"[0.005559503140102689, 10.630848932317774]","[0.6733204005580575, 0.9402321095180544]",5.318204e+00,0.806776,"[0.13160299555970648, 0.9389246496470462]","[0.3772803859482321, 0.9993979355571085]",0.535264,0.688339,"[1.603641298128818, 8818.1903718599]","[1.0578088692267382, 0.9998588795073206]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_lmOGuWs9,"[189.12076064880057, 18.93392593481769]","[0.9977258456841748, 0.9999949283520131]",1.040273e+02,0.998860,"[0.9981992972281647, 0.9353296301076058]","[0.99889889326794, 0.9997888190445553]",0.966764,0.999344,"[1.0381167565747864, 1253.0520889700522]","[0.7743869696042152, 1.0061575223346375]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_oVLbHSe1,"[0.0866918366220469, 10.838955889729625]","[0.0023528108563422964, 0.008692083781786911]",5.462824e+00,0.005522,"[0.1073291227652575, 0.3729043328692463]","[0.13940995369149217, 0.12106403015773516]",0.240117,0.130237,"[2.747064315121089, 902.9736963318553]","[1.2251986558474215, 0.9996276616375744]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_ow0vRVA0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_plAVbXsz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_puUxHMQN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_t9P2cULj,"[0.015726159359047524, 57.183918848425435]","[0.001480285492817961, 0.04132704151788958]",2.859982e+01,0.021404,"[0.2818170659245788, 0.3699615911321166]","[0.3293540472331495, 0.15508432112863618]",0.325889,0.242219,"[1.0249019969853161, 4.64495574383555]","[1.060008496537618, 1.000319198677067]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_tyZFWhCJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_vIaowdVW,"[0.003785034024521166, 4.259496459545917]","[0.6618557779628842, 0.9331348627936885]",2.131641e+00,0.797495,"[0.11806289845833658, 0.024418058645945415]","[0.23616524989187612, 0.9967128787002528]",0.071240,0.616439,"[1.6069904718845374, 572.6583576177843]","[1.6296433486073554, 0.9996390909358297]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_vZmPj6TF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_whH96Zz8,"[6.949999981805394, 1.0403651338613782]","[0.9607660574876525, 1.0000024531454261]",3.995183e+00,0.980384,"[0.996372198822073, 1.0243886864580802]","[0.9964756842670889, 0.9998115790967281]",1.010380,0.998144,"[2520.4002249267264, 99076.38557329142]","[241.75822710272823, 0.9789982235033191]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_xtfL5l2T,"[15.715896633015591, 6.814688863368531]","[0.9778432428462277, 1.000005603343657]",1.126529e+01,0.988924,"[0.996798869125568, 0.9580335628576526]","[0.9980396997226857, 0.9997401883349015]",0.977416,0.998890,"[5020.90635174051, 22574122.65553941]","[714.2299081197654, 3.564369771670393]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_yU8wxo41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_ymsRpwaq,"[0.2140858998630332, 68.13705553232458]","[0.3652780558951259, 0.256222213059135]",3.417557e+01,0.310750,"[1.436163550968426, 0.8272709847289196]","[24.12056299736634, 0.699262862854182]",1.131717,12.409913,"[1.1145381883448073, 38.35509220644244]","[1.0427385887856073, 1.000017675027972]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN

In [14]:
problems = ['vanderpol', 'pollu', 'rober', 'orego', 'hires', 'davis-skodje'] 
problem = problems[0]


df = DB[(DB["problem"] == problem)]
print(df["seed"].unique())
df = df[df["seed"] == 12]
COLS = ["seed", "training", "model", "pretraining"]
# sort by seed and then by model
# display(df.sort_values(by=["seed", "E_trajectory_train"])[COLS])
# display(df.sort_values(by=["seed", "E_spec_train"])[COLS])
# display(df.sort_values(by=["seed", "E_VF_train"])[COLS])
# display(df.sort_values(by=["seed", "E_trajectory_species_test"])[COLS])
display(df.sort_values(by=["E_trajectory_test"])[COLS])
display(df.sort_values(by=["E_spec_test"])[COLS])
display(df.sort_values(by=["E_VF_test"])[COLS])
display(df.sort_values(by=["E_trajectory_species_test"])[COLS])

[ 15  11  13  14  12 123]

              seed     training        model pretraining
run_dir
run_2cXb4Ci9    12     shooting  GELU-scaled  derivmatch
run_kpAH7mr1    12     shooting          mlp        none
run_2KX3LvwX    12         none        stiff  derivmatch
run_V8vGwpsd    12         none        stiff  derivmatch
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_t9P2cULj    12         none  GELU-scaled  derivmatch
run_hP77gWym    12  collocation  GELU-scaled  derivmatch
run_2Jf27enp    12     shooting        stiff        none
run_IJaad5HS    12     shooting        stiff        none
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_59oWj9tF    12  collocation        stiff        none
run_fYLeYU4y    12  collocation        stiff        none
run_4UfHofXn    12     shooting        stiff  derivmatch
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_IzVyuqsi    12     shooting  GELU-scaled        none
run_vIaowdVW    12         none          mlp  derivmatch
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_a2uHaghT    12  collocation        stiff  derivmatch
run_lmOGuWs9    12     shooting          mlp        none
run_kKtsBFQg    12  collocation          mlp  derivmatch
run_X8H6w7Nv    12         none          mlp  derivmatch
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_Yk23lx21    12     shooting  GELU-scaled        none
run_whH96Zz8    12  collocation          mlp        none
run_4Q869pti    12  collocation  GELU-scaled        none
run_xtfL5l2T    12  collocation          mlp        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none

              seed     training        model pretraining
run_dir
run_vIaowdVW    12         none          mlp  derivmatch
run_kKtsBFQg    12  collocation          mlp  derivmatch
run_a2uHaghT    12  collocation        stiff  derivmatch
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_hP77gWym    12  collocation  GELU-scaled  derivmatch
run_t9P2cULj    12         none  GELU-scaled  derivmatch
run_2KX3LvwX    12         none        stiff  derivmatch
run_V8vGwpsd    12         none        stiff  derivmatch
run_X8H6w7Nv    12         none          mlp  derivmatch
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_lmOGuWs9    12     shooting          mlp        none
run_xtfL5l2T    12  collocation          mlp        none
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_Yk23lx21    12     shooting  GELU-scaled        none
run_IzVyuqsi    12     shooting  GELU-scaled        none
run_4Q869pti    12  collocation  GELU-scaled        none
run_whH96Zz8    12  collocation          mlp        none
run_kpAH7mr1    12     shooting          mlp        none
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_2cXb4Ci9    12     shooting  GELU-scaled  derivmatch
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_4UfHofXn    12     shooting        stiff  derivmatch
run_59oWj9tF    12  collocation        stiff        none
run_fYLeYU4y    12  collocation        stiff        none
run_IJaad5HS    12     shooting        stiff        none
run_2Jf27enp    12     shooting        stiff        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none

              seed     training        model pretraining
run_dir
run_4Q869pti    12  collocation  GELU-scaled        none
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_kKtsBFQg    12  collocation          mlp  derivmatch
run_vIaowdVW    12         none          mlp  derivmatch
run_IzVyuqsi    12     shooting  GELU-scaled        none
run_whH96Zz8    12  collocation          mlp        none
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_X8H6w7Nv    12         none          mlp  derivmatch
run_a2uHaghT    12  collocation        stiff  derivmatch
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_2KX3LvwX    12         none        stiff  derivmatch
run_V8vGwpsd    12         none        stiff  derivmatch
run_xtfL5l2T    12  collocation          mlp        none
run_Yk23lx21    12     shooting  GELU-scaled        none
run_hP77gWym    12  collocation  GELU-scaled  derivmatch
run_t9P2cULj    12         none  GELU-scaled  derivmatch
run_kpAH7mr1    12     shooting          mlp        none
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_lmOGuWs9    12     shooting          mlp        none
run_2cXb4Ci9    12     shooting  GELU-scaled  derivmatch
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_4UfHofXn    12     shooting        stiff  derivmatch
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_59oWj9tF    12  collocation        stiff        none
run_fYLeYU4y    12  collocation        stiff        none
run_IJaad5HS    12     shooting        stiff        none
run_2Jf27enp    12     shooting        stiff        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none

              seed     training        model pretraining
run_dir
run_kpAH7mr1    12     shooting          mlp        none
run_4UfHofXn    12     shooting        stiff  derivmatch
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_2cXb4Ci9    12     shooting  GELU-scaled  derivmatch
run_59oWj9tF    12  collocation        stiff        none
run_fYLeYU4y    12  collocation        stiff        none
run_2Jf27enp    12     shooting        stiff        none
run_IJaad5HS    12     shooting        stiff        none
run_t9P2cULj    12         none  GELU-scaled  derivmatch
run_hP77gWym    12  collocation  GELU-scaled  derivmatch
run_lmOGuWs9    12     shooting          mlp        none
run_4Q869pti    12  collocation  GELU-scaled        none
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_IzVyuqsi    12     shooting  GELU-scaled        none
run_kKtsBFQg    12  collocation          mlp  derivmatch
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_X8H6w7Nv    12         none          mlp  derivmatch
run_vIaowdVW    12         none          mlp  derivmatch
run_Yk23lx21    12     shooting  GELU-scaled        none
run_V8vGwpsd    12         none        stiff  derivmatch
run_2KX3LvwX    12         none        stiff  derivmatch
run_a2uHaghT    12  collocation        stiff  derivmatch
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_whH96Zz8    12  collocation          mlp        none
run_xtfL5l2T    12  collocation          mlp        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none

In [19]:
for problem in DB["problem"].unique():
      print(f"Problem: {problem}")
      subset = DB[DB["problem"] == problem]
      for model, group in subset.groupby("model", dropna=False):
          n_params = group["n_params"].dropna()
          if n_params.empty:
              print(f"  Model: {model}, n_params: missing")
          else:
              print(f"  Model: {model}, n_params: {n_params.iloc[0]}")

Problem: rober
  Model: GELU-scaled, n_params: 188
  Model: mlp, n_params: 348
  Model: stiff, n_params: 318
Problem: vanderpol
  Model: GELU-scaled, n_params: 317
  Model: mlp, n_params: 282
  Model: stiff, n_params: 268
  Model: nan, n_params: 268
Problem: pollu
  Model: GELU-scaled, n_params: 650
  Model: mlp, n_params: 3444
  Model: stiff, n_params: 4744
Problem: hires
  Model: GELU-scaled, n_params: 855
  Model: mlp, n_params: 827
  Model: stiff, n_params: 816
Problem: orego
  Model: GELU-scaled, n_params: 188
  Model: mlp, n_params: 387
  Model: stiff, n_params: 486
Problem: davis-skodje
  Model: GELU-scaled, n_params: 317
  Model: mlp, n_params: 282
  Model: stiff, n_params: 268

In [20]:
for problem in DB["problem"].unique():
    print(f"Problem: {problem}")
    subset = DB[DB["problem"] == problem]
    for model, group in subset.groupby("model", dropna=False):
        n_params_vals = sorted(group["n_params"].dropna().unique())
        if not n_params_vals:
            print(f"  Model: {model}, n_params: missing")
        else:
            print(f"  Model: {model}, n_params: {n_params_vals}")

Problem: rober
  Model: GELU-scaled, n_params: [188, 332]
  Model: mlp, n_params: [243, 348]
  Model: stiff, n_params: [318]
Problem: vanderpol
  Model: GELU-scaled, n_params: [177, 317]
  Model: mlp, n_params: [218, 282]
  Model: stiff, n_params: [268]
  Model: nan, n_params: [268]
Problem: pollu
  Model: GELU-scaled, n_params: [650, 4940]
  Model: mlp, n_params: [3444, 4940]
  Model: stiff, n_params: [4744]
Problem: hires
  Model: GELU-scaled, n_params: [243, 855]
  Model: mlp, n_params: [552, 827]
  Model: stiff, n_params: [816]
Problem: orego
  Model: GELU-scaled, n_params: [188, 516]
  Model: mlp, n_params: [387, 516]
  Model: stiff, n_params: [486]
Problem: davis-skodje
  Model: GELU-scaled, n_params: [177, 317]
  Model: mlp, n_params: [218, 282]
  Model: stiff, n_params: [268]