In [1]:
import pandas as pd

In [5]:
DB_PATH = "runs_index.csv"

DB = pd.read_csv(DB_PATH, index_col=0)
DB.head()

,E_VF_species_test,E_VF_species_train,E_VF_test,E_VF_train,E_spec_species_test,E_spec_species_train,E_spec_test,E_spec_train,E_trajectory_species_test,E_trajectory_species_train,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_08Q75yMZ,"[10446623.782296566, 1194.5543581813756]","[10.715507911567633, 1.5986795653726147]",5.223909e+06,6.157094,"[0.5359738312047515, 19239.064993098116]","[0.6441668171710596, 3.827308649691848]",9.619800e+03,2.235738,"[0.9999085679779263, 1.2339071350922954]","[0.9141669227994335, 1.0000010983614722]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_09nnvX1K,"[1.2659853792184483, 0.27912456983322287, 1768...","[9.478247367860889e-08, 9.053455205637821e-08,...",1.054764e+29,0.691589,"[0.9999999999833352, 0.9999996564257434, 0.997...","[0.9999999993400052, 0.9999993127647504, 0.993...",2.368737e+304,inf,"[6657491.871020809, 1914071.3614436523, 9.6802...","[687993.1519896915, 15090.967524426405, 8.8297...",...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_0BLmyHm6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,False,NaN,NaN,NaN,NaN,NaN
run_0BrnUKSf,"[0.003491629023558983, 0.0003463697886834507, ...","[0.0021643198830668007, 0.00010993092834579057...",1.365435e-03,0.000818,"[0.9945019265279103, 0.9960549157827169, 0.891...","[0.9901279029706659, 0.8112164424005774, 1.282...",9.606980e-01,1.027826,"[1.0753848000133974, 0.7632131151812649, 1.049...","[1.0886067949684322, 9.955692466227957, 0.9269...",...,2,10000,16,150,False,NaN,NaN,NaN,NaN,NaN
run_0CWrKVsW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,False,NaN,NaN,NaN,NaN,NaN

In [6]:
DB.info()

<class 'pandas.core.frame.DataFrame'>
Index: 998 entries, run_08Q75yMZ to run_zqUT4Zrb
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   E_VF_species_test           420 non-null    object
 1   E_VF_species_train          420 non-null    object
 2   E_VF_test                   402 non-null    float64
 3   E_VF_train                  418 non-null    float64
 4   E_spec_species_test         420 non-null    object
 5   E_spec_species_train        420 non-null    object
 6   E_spec_test                 402 non-null    float64
 7   E_spec_train                418 non-null    float64
 8   E_trajectory_species_test   420 non-null    object
 9   E_trajectory_species_train  420 non-null    object
 10  E_trajectory_test           402 non-null    float64
 11  E_trajectory_train          418 non-null    float64
 12  collocation_time            998 non-null    float64
 13  computer                    995 non-null    object
 14  derivmatch_time             998 non-null    float64
 15  err-file                    995 non-null    object
 16  init                        996 non-null    object
 17  model                       996 non-null    object
 18  n_params                    998 non-null    int64
 19  ncol                        996 non-null    float64
 20  out-file                    995 non-null    object
 21  param                       998 non-null    object
 22  pretraining                 995 non-null    object
 23  problem                     998 non-null    object
 24  profile                     998 non-null    object
 25  seed                        998 non-null    int64
 26  shap-hessian                504 non-null    object
 27  shapovalova_time            996 non-null    float64
 28  shoot-iters                 996 non-null    float64
 29  shooting_time               996 non-null    float64
 30  sigma                       996 non-null    float64
 31  timestamp                   996 non-null    object
 32  training                    995 non-null    object
 33  training_time               998 non-null    float64
 34  cfg.amr_rounds              998 non-null    int64
 35  cfg.depth                   998 non-null    int64
 36  cfg.dm_iters                998 non-null    int64
 37  cfg.hidden                  998 non-null    int64
 38  cfg.lm_iters                998 non-null    int64
 39  cfg.signed_loss             998 non-null    bool
 40  cfg.linsolve                183 non-null    object
 41  use_collocation             3 non-null      object
 42  use_derivmatch              3 non-null      object
 43  shapovalova                 1 non-null      object
 44  shooting                    1 non-null      object
dtypes: bool(1), float64(14), int64(7), object(23)
memory usage: 351.8+ KB

In [7]:
print(DB["model"].unique())
print(DB["problem"].unique())
print(DB["pretraining"].unique())
print(DB["training"].unique())

['stiff' 'mlp' 'GELU-scaled' nan]
['vanderpol' 'pollu' 'rober' 'orego' 'hires' 'davis-skodje']
['none' 'derivmatch' nan]
['shooting' 'collocation' 'none' 'shapovalova' nan]

In [43]:
DB[["model", "training", "pretraining"]].drop_duplicates()

                    model     training pretraining
run_dir
run_08Q75yMZ        stiff     shooting        none
run_09nnvX1K          mlp  collocation        none
run_0BLmyHm6          mlp         none  derivmatch
run_0BrnUKSf        stiff         none  derivmatch
run_0CWrKVsW  GELU-scaled         none  derivmatch
run_0Gfl62cO  GELU-scaled  collocation        none
run_0H5EbMNc        stiff  collocation  derivmatch
run_0HTw2xgv        stiff  collocation        none
run_0Lq1bPrm          mlp  shapovalova  derivmatch
run_0ilswGVa  GELU-scaled  shapovalova        none
run_0oHxpKt3          mlp  shapovalova        none
run_0pAVzUCM        stiff  shapovalova  derivmatch
run_0pSCJcJK          mlp     shooting        none
run_0tGVJv8Q  GELU-scaled     shooting        none
run_0zFIEZKM          mlp  collocation  derivmatch
run_1zqChve1  GELU-scaled  collocation  derivmatch
run_2r6WutKj  GELU-scaled     shooting  derivmatch
run_2tL35rX6  GELU-scaled  shapovalova  derivmatch
run_3LMT5OkW          mlp     shooting  derivmatch
run_3Pph53ey        stiff     shooting  derivmatch
run_9ZBK1iOn        stiff  shapovalova        none
run_9zWKNJ3v          NaN          NaN         NaN
run_Uve46cZI        stiff          NaN         NaN

In [8]:
nn = DB[(DB["problem"] == "vanderpol") & (DB["model"] == "stiff") & (DB["pretraining"] == "derivmatch") & (DB["training"] == "collocation")]
nn = DB[(DB["problem"] == "pollu") & (DB["model"] == "stiff") & (DB["pretraining"] == "derivmatch") & (DB["training"] == "collocation")]
nn

,E_VF_species_test,E_VF_species_train,E_VF_test,E_VF_train,E_spec_species_test,E_spec_species_train,E_spec_test,E_spec_train,E_trajectory_species_test,E_trajectory_species_train,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_3Dvf3Sjs,"[0.03791009454908303, 0.018159627599197474, 15...","[0.00029014922586677924, 0.0001348290395190628...",1.270655e+08,0.100517,"[0.9999999991306496, 0.999999869279478, 0.9998...","[0.9999999968352407, 0.9999716625343635, 0.975...",2.706855e+302,1.639589e+302,"[0.00011397283220663385, 5.2926734384272484e-0...","[1.7392092557402147e-05, 3.5942942017934874e-0...",...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_B8TA6bwb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_DpEiOWTX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_IDVpnloi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_JJsUwKiA,"[0.06832167969278968, 0.03594630400169694, 859...","[6.527455823145166e-05, 0.00010467774321531233...",2.669403e+08,0.101394,"[0.9999999990614183, 0.9999998828520323, 0.999...","[0.9999999984763857, 0.9999628293504128, 0.969...",1.391690e+300,1.275827e+302,"[0.00015718360340149533, 8.740524737526633e-05...","[2.3239677796754014e-05, 3.5824544778916246e-0...",...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_fVbSaGWP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_iVKN0IRG,"[0.12964642951599012, 0.10524087643785573, 182...","[1.923677459050495e-05, 4.184475067662265e-05,...",9.386856e+07,0.099928,"[0.9999999991185407, 0.999999842555881, 0.9999...","[0.999999998112611, 0.9999261933107896, 0.9373...",1.138398e+302,2.258923e+302,"[0.0006299475587867902, 0.0003962305128377852,...","[7.511080750303588e-07, 3.084801651755378e-08,...",...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_xskaaKrJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN

In [9]:
DB.keys()

Index(['E_VF_species_test', 'E_VF_species_train', 'E_VF_test', 'E_VF_train',
       'E_spec_species_test', 'E_spec_species_train', 'E_spec_test',
       'E_spec_train', 'E_trajectory_species_test',
       'E_trajectory_species_train', 'E_trajectory_test', 'E_trajectory_train',
       'collocation_time', 'computer', 'derivmatch_time', 'err-file', 'init',
       'model', 'n_params', 'ncol', 'out-file', 'param', 'pretraining',
       'problem', 'profile', 'seed', 'shap-hessian', 'shapovalova_time',
       'shoot-iters', 'shooting_time', 'sigma', 'timestamp', 'training',
       'training_time', 'cfg.amr_rounds', 'cfg.depth', 'cfg.dm_iters',
       'cfg.hidden', 'cfg.lm_iters', 'cfg.signed_loss', 'cfg.linsolve',
       'use_collocation', 'use_derivmatch', 'shapovalova', 'shooting'],
      dtype='object')

In [10]:
vdp1 = DB[(DB["problem"] == "vanderpol") & (DB["seed"] == 123)]
vdp1

,E_VF_species_test,E_VF_species_train,E_VF_test,E_VF_train,E_spec_species_test,E_spec_species_train,E_spec_test,E_spec_train,E_trajectory_species_test,E_trajectory_species_train,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_9zWKNJ3v,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,False,True,NaN,NaN
run_Ez3T7npt,"[0.0025658761273894045, 7.851168470428202]","[0.00024233537898191493, 0.0032099468712698375]",3.926867,0.001726,"[0.048033674927017204, 0.03158068792901949]","[0.024475651553433356, 0.1440329762444342]",0.039807,0.084254,"[0.04968781619953609, 55779.52593749643]","[0.01630848152930572, 0.46239267905412423]",...,2,10000,12,150,True,NaN,NaN,NaN,NaN,NaN
run_FbGbX3v0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,False,True,NaN,NaN
run_Uve46cZI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,10000,12,150,True,NaN,False,True,False,False

In [44]:
problems = ['vanderpol', 'pollu', 'rober', 'orego', 'hires', 'davis-skodje'] 
problem = problems[0]


df = DB[(DB["problem"] == problem)]
print(df["seed"].unique())
df = df[df["seed"] == 12]
COLS = ["seed", "training", "model", "pretraining"]
# sort by seed and then by model
# display(df.sort_values(by=["seed", "E_trajectory_train"])[COLS])
# display(df.sort_values(by=["seed", "E_spec_train"])[COLS])
# display(df.sort_values(by=["seed", "E_VF_train"])[COLS])
# display(df.sort_values(by=["seed", "E_trajectory_species_test"])[COLS])
display(df.sort_values(by=["E_trajectory_test"])[COLS])
display(df.sort_values(by=["E_spec_test"])[COLS])
display(df.sort_values(by=["E_VF_test"])[COLS])
display(df.sort_values(by=["E_trajectory_species_test"])[COLS])

[ 15  11  13  14  12 123]

              seed     training        model pretraining
run_dir
run_kpAH7mr1    12     shooting          mlp        none
run_V8vGwpsd    12         none        stiff  derivmatch
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_IJaad5HS    12     shooting        stiff        none
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_59oWj9tF    12  collocation        stiff        none
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_X8H6w7Nv    12         none          mlp  derivmatch
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_Yk23lx21    12     shooting  GELU-scaled        none
run_xtfL5l2T    12  collocation          mlp        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none

              seed     training        model pretraining
run_dir
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_V8vGwpsd    12         none        stiff  derivmatch
run_X8H6w7Nv    12         none          mlp  derivmatch
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_xtfL5l2T    12  collocation          mlp        none
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_Yk23lx21    12     shooting  GELU-scaled        none
run_kpAH7mr1    12     shooting          mlp        none
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_59oWj9tF    12  collocation        stiff        none
run_IJaad5HS    12     shooting        stiff        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none

              seed     training        model pretraining
run_dir
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_X8H6w7Nv    12         none          mlp  derivmatch
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_V8vGwpsd    12         none        stiff  derivmatch
run_xtfL5l2T    12  collocation          mlp        none
run_Yk23lx21    12     shooting  GELU-scaled        none
run_kpAH7mr1    12     shooting          mlp        none
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_59oWj9tF    12  collocation        stiff        none
run_IJaad5HS    12     shooting        stiff        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none

              seed     training        model pretraining
run_dir
run_kpAH7mr1    12     shooting          mlp        none
run_CUNu6zUG    12     shooting        stiff  derivmatch
run_59oWj9tF    12  collocation        stiff        none
run_IJaad5HS    12     shooting        stiff        none
run_FIICVUPQ    12         none  GELU-scaled  derivmatch
run_ymsRpwaq    12  collocation  GELU-scaled  derivmatch
run_dmG8mHuF    12  collocation  GELU-scaled        none
run_V4foGNTC    12     shooting  GELU-scaled  derivmatch
run_X8H6w7Nv    12         none          mlp  derivmatch
run_l9XKFt0b    12  collocation          mlp  derivmatch
run_Yk23lx21    12     shooting  GELU-scaled        none
run_V8vGwpsd    12         none        stiff  derivmatch
run_oVLbHSe1    12  collocation        stiff  derivmatch
run_xtfL5l2T    12  collocation          mlp        none
run_1MJPRoKf    12     shooting          mlp        none
run_4MRZ6jvw    12     shooting  GELU-scaled        none
run_6htkcYWO    12  collocation          mlp  derivmatch
run_6kcc1goF    12  shapovalova  GELU-scaled        none
run_9ZD8cDMb    12  shapovalova        stiff        none
run_BdmsU23Q    12         none  GELU-scaled  derivmatch
run_ByrM0GZ8    12     shooting        stiff  derivmatch
run_CCc8Tb1V    12  shapovalova        stiff  derivmatch
run_CMR4BCYC    12  shapovalova          mlp        none
run_JgGyD6Qb    12  collocation  GELU-scaled        none
run_N6ki4SLO    12  shapovalova          mlp  derivmatch
run_NbHfewgV    12  shapovalova  GELU-scaled  derivmatch
run_S3pDx8Dc    12     shooting  GELU-scaled  derivmatch
run_YbW9DQXs    12  shapovalova          mlp        none
run_bm0tMVBA    12  shapovalova        stiff  derivmatch
run_f01RPzsB    12         none          mlp  derivmatch
run_gKwo4E3L    12  collocation        stiff        none
run_hFI32hy7    12  shapovalova  GELU-scaled        none
run_hqsYpKzi    12  shapovalova  GELU-scaled  derivmatch
run_i86bSKOp    12  shapovalova          mlp  derivmatch
run_ow0vRVA0    12  collocation          mlp        none
run_plAVbXsz    12  collocation        stiff  derivmatch
run_puUxHMQN    12  collocation  GELU-scaled  derivmatch
run_tyZFWhCJ    12         none        stiff  derivmatch
run_vZmPj6TF    12  shapovalova        stiff        none
run_yU8wxo41    12     shooting        stiff        none