In [1]:
import pandas as pd

In [2]:
DB_PATH = "runs_index.csv"

DB = pd.read_csv(DB_PATH, index_col=0)
DB.head()

,collocation_time,derivmatch_time,n_params,param,problem,profile,seed,training_time,use_collocation,use_derivmatch,cfg.amr_rounds,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss
run_dir,,,,,,,,,,,,,,,,
run_9zWKNJ3v,0.0,13.560064,268,100.0,vanderpol,fast,123,13.560064,False,True,1,2,10000,12,150,True
run_FbGbX3v0,0.0,12.932799,268,100.0,vanderpol,fast,123,12.932799,False,True,1,2,10000,12,150,True

In [3]:
DB.keys()

Index(['collocation_time', 'derivmatch_time', 'n_params', 'param', 'problem',
       'profile', 'seed', 'training_time', 'use_collocation', 'use_derivmatch',
       'cfg.amr_rounds', 'cfg.depth', 'cfg.dm_iters', 'cfg.hidden',
       'cfg.lm_iters', 'cfg.signed_loss'],
      dtype='object')

In [6]:
vdp1 = DB[(DB["problem"] == "vanderpol") & (DB["seed"] == 123)]
vdp1

,collocation_time,derivmatch_time,n_params,param,problem,profile,seed,training_time,use_collocation,use_derivmatch,cfg.amr_rounds,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss
run_dir,,,,,,,,,,,,,,,,
run_9zWKNJ3v,0.0,13.560064,268,100.0,vanderpol,fast,123,13.560064,False,True,1,2,10000,12,150,True
run_FbGbX3v0,0.0,12.932799,268,100.0,vanderpol,fast,123,12.932799,False,True,1,2,10000,12,150,True